#! /usr/local/bin/guile -s
!#
;;;;
;;;; 	Copyright (C) 2010 Neil Jerram.
;;;; 
;;;; This library is free software; you can redistribute it and/or
;;;; modify it under the terms of the GNU General Public License as
;;;; published by the Free Software Foundation; either version 3 of
;;;; the License, or (at your option) any later version.
;;;; 
;;;; This library is distributed in the hope that it will be useful,
;;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;;; General Public License for more details.
;;;; 
;;;; You should have received a copy of the GNU General Public License
;;;; along with this library; if not, write to the Free Software
;;;; Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
;;;; 02110-1301 USA
                                             ; -*- scheme -*-
(set! %load-path (cons "/home/neil/Guile/guile-ossau-0.7" %load-path))

(use-modules (ice-9 readline))
(activate-readline)

(use-modules (ossau affiche))

(display "Welcome to Guile/Affiche - using Guile ")
(display (version))
(newline)

(affiche)
